### ISSUE TITLE
Crash when there is an MKMapView in a collection view cell

### ISSUE THREAD

**Issue by jznadams** [kif-framework/KIF#802]
I have a view controller with a collection view, and one of the collection view cells has an MKMapView inside of it. Whenever I attempt to call waitForViewWithAccessibilityLabel: or tapViewWithAccessibilityLabel: when this view controller is visible, KIF will crash on line 195 of UIView-KIFAdditions.m (inside of accessibilityElementMatchingBlock:notHidden:). It seems to be stuck inside of a deep loop searching for the accessibility label I have referenced, but just dies when it encounters the map instance:

![screen shot 2016-02-24 at 6 21 19 pm](https://cloud.githubusercontent.com/assets/162983/13305018/5ec38b28-db26-11e5-9221-0d9485502367.png)

If I set the hidden property of the map to true, everything works fine and my test passes successfully ( although it still takes several seconds to find the view on this particular screen). I have no interest in actually interacting with the map in my test, I'm just trying to trigger a touch event in another button on the screen. Any ideas?

**Comment by phatmann** [comment]
Nice catch, thanks for the details so far. Can you tell me which call involving MKMapView is crashing?

**Comment by jznadams** [comment]
It's crashing while trying to call accessibilityElementCount on a MKBasicMapView instance, which appears to be a private inner class of the regular map view. The trace stack looks weird, it looks like some of the instances that are being iterated through have been freed by the OS. For example, the elementStack variable in the screenshot above is nil if I hover the mouse over it.  if I go higher up the call tree, I see lots of nils for the elements. Maybe it's related to the map view initializing? The control itself is flashing rapidly as it tries to zoom in on the GPS coordinates.

**Comment by mikelupo** [comment]
I have a similar problem. I outlined it in this link.
[KIFCrash](https://groups.google.com/forum/#!topic/kif-framework/eoIod-Deq-8)

**Comment by phatmann** [comment]
I posted a comment in the forum discussion referenced above, and I will repeat a similar comment here. 

An argument was made a while back that KIF should not find views with an alpha of 0 (#190). The response from @bnickel: _alpha is simply a one aspect of a view's visibility. A 0 alpha view may still be tappable or announced by a VoiceOver. hidden is the correct way to make a view "absent”_

So, is the MKMapView tappable or discoverable by VoiceOver? If not, then KIF is doing it wrong and this should be fixed.

**Comment by percysnoodle** [comment]
I've just run into this.  I don't think it has anything to do with alpha values.  I'm seeing the same problem in accessibilityElementCount as @jznadams.

**Comment by mikelupo** [comment]
I'm still encountering EXC_BAD_ACCESS crashes on line 195 of UIView-KIFAdditions.m:
NSInteger accessibilityElementCount = element.accessibilityElementCount;
element is a JCTableViewCell. 

`#0	0x397e8f56 in objc_msgSend ()
#1	0x29950504 in -[UITableViewCellAccessibility _accessibilityChildren] ()
#2	0x299519c2 in -[UITableViewCellAccessibility accessibilityElementCount] ()
#3	0x043f2660 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:195
#4	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#5	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#6	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#7	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#8	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#9	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#10	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#11	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#12	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#13	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#14	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#15	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#16	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#17	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#18	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#19	0x043f21b2 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:notHidden:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:158
#20	0x043f1e26 in -[UIView(KIFAdditions) accessibilityElementMatchingBlock:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:127
#21	0x043f154a in -[UIView(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIView-KIFAdditions.m:102
#22	0x043edcf8 in -[UIApplication(KIFAdditions) accessibilityElementWithLabel:accessibilityValue:traits:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIApplication-KIFAdditions.m:44
#23	0x043ea6da in +[UIAccessibilityElement(KIFAdditions) accessibilityElementWithLabel:value:traits:error:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIAccessibilityElement-KIFAdditions.m:83
#24	0x043ea15a in +[UIAccessibilityElement(KIFAdditions) accessibilityElement:view:withLabel:value:traits:tappable:error:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Additions/UIAccessibilityElement-KIFAdditions.m:43
#25	0x0440077a in __110-[KIFUITestActor(ConditionalTests) tryFindingAccessibilityElement:view:withLabel:value:traits:tappable:error:]_block_invoke at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Classes/KIFUITestActor-ConditionalTests.m:53
#26	0x043fb4a8 in -[KIFTestActor tryRunningBlock:complete:timeout:error:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Classes/KIFTestActor.m:51
#27	0x044006a0 in -[KIFUITestActor(ConditionalTests) tryFindingAccessibilityElement:view:withLabel:value:traits:tappable:error:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Classes/KIFUITestActor-ConditionalTests.m:52
#28	0x0440050e in -[KIFUITestActor(ConditionalTests) tryFindingViewWithAccessibilityLabel:value:traits:tappable:error:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Classes/KIFUITestActor-ConditionalTests.m:47
#29	0x04400270 in -[KIFUITestActor(ConditionalTests) tryFindingTappableViewWithAccessibilityLabel:error:] at /Users/tester/Documents/TheProject/TestFrameworks/KIF/Classes/KIFUITestActor-ConditionalTests.m:32
#30	0x043bde78 in -[KIFUITestActor(KIF_Automation_Helper) promiscuouslyNavigateBackToScreenName:WithTimeout:] at /Users/tester/Documents/TheProject/UIAutomationTests/KIF_Automation_Helper.m:105
#31	0x043bf208 in -[KIFUITestActor(KIF_Automation_Helper) promiscuouslyNavigateBackToGridViewWithTimeout:] at /Users/tester/Documents/TheProject/UIAutomationTests/KIF_Automation_Helper.m:181
#32	0x043bf1a2 in -[KIFUITestActor(KIF_Automation_Helper) promiscuouslyNavigateBackToGridView] at /Users/tester/Documents/TheProject/UIAutomationTests/KIF_Automation_Helper.m:176
#33	0x04370456 in -[SettingsTests test002DevicePolicyAutoplayLastVideo] at /Users/tester/Documents/TheProject/UIAutomationTests/SettingsTests.m:259`
